### PR TITLE
fixes #96

### LINKED ISSUE #96: Heap pollution in JobScheduler
Redundant creation of Long wrappers due to typed ThreadLocal. For such a frequent task we should use primitives.

### PR DESCRIPTION
**Pull request by clumsy**
using primitive holder for JobScheduler's start time

### CODE REVIEW

**Comment by VISTALL** [comment]
I am sure need fix it. What do u think about AtomicLong using as generic argument? 

it have **get** & **set** method which not used unsafe context.

**Comment by clumsy** [comment]
Using an AtomicLong in generic parameter is equivalent to my patch, feel free to choose your favourite.
It has the same guarantees we need. Just make sure it's created once per thread (that is in initialValue as in my patch) and change the contents of a get() of ThreadLocal.

**Comment by VISTALL** [comment]
Code more cleaner. As IntellJ code style, need provide field with prefix **my** and accessors, due 

```
START.get().myTime = System.currentTimeMillies();
```

I thk i wil change code to correct code style(idk why they pushed in to JB with wrong code style)

**Comment by clumsy** [comment]
If styling is involved, I suggest to go with AtomicLong and be done with it. Do you want me to send the equivalent patch using AtomicLong?

**Comment by VISTALL** [comment]
I will push it by self

**Comment by clumsy** [comment]
OK, just in case - I've pushed it to my pull request branch too.

**Comment by VISTALL** [comment]
done

**Pull request closed without merging**
