### PR TITLE
fixes #69

### LINKED ISSUE #69: Consulo fails to launch with java 1.7+
When changing java version from 1.6* to 1.7* in Info.plist it finally starts.
I would have thought 1.6* covers 1.7 as well. I'd rather fix this or specify that it ONLY works for 1.6 java.

### PR DESCRIPTION
**Pull request by clumsy**
using 1.6+ JVM version rather than 1.6 only

### CODE REVIEW

**Comment by VISTALL** [comment]
You tested ? It helps?

**Comment by clumsy** [comment]
It helped me run the app on my 1.7.0_51 without the need to change Info.plist (that is as is). I can also check using 1.6 and 1.8 java if you like.

I was using this info: https://developer.apple.com/library/mac/documentation/Java/Reference/Java_InfoplistRef/Articles/JavaDictionaryInfo.plistKeys.html

Here are a few excerpts: 

String | Java version used | Notes
---------|-------------------------|----------
1.6* | 6 | Specifies the highest version of Java SE 6 available. If no version of Java SE 6 is present, the default version of Java in Java Preferences is used. **This string is not recommended**.
1.6+ | 6 | Specifies the highest version of Java above Java SE 6. Note that if is updated in future releases of OS X, the latest version of Java is used.

**Note**: The Java Preferences application, in /Applications/Utilities/, determines how these keys are interpreted. Users can change a precedence list that determines how the keys ending in a plus sign are interpreted. If a user places J2SE 1.4.2 over J2SE 5.0 in the precedence list, the 1.4+ key results in J2SE 1.4.2 being used for the application.

Thought there's also an option to remove this property altogether:
**Note**:  If you do not set the JVMVersion key in a double clickable application, it runs in the first compatible version of Java specified by the user in the precedence list in the Java Preferences application.

But I guess the code might require JVM no lower than 1.6 (that's why the JVMVersion was set in the first place).

**Comment by VISTALL** [comment]
>> I can also check using 1.6 and 1.8 java if you like.

Yep will be good

**Comment by clumsy** [comment]
Confirmed:
screen shot 2015-03-10 at 22 53 09
screen shot 2015-03-10 at 21 40 23
screen shot 2015-03-10 at 22 54 46

**Comment by clumsy** [comment]
though found another issue in mac launcher.

**Comment by VISTALL** [comment]
Ok merged

**Comment by VISTALL** [comment]
Thanks

**Pull request merged**
